---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic-stack
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
          ports:
            - containerPort: 9200
          env:
            - name: "ES_JAVA_OPTS"
              value: "-Xms1g -Xmx1g"

            - name: XPACK_SECURITY_ENABLED
              value: "false"

            - name: "discovery.type"
              value: "single-node"


---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic-stack
spec:
  selector:
    app: elasticsearch
  ports:
    - name: es1
      protocol: TCP
      port: 9200

    - name: es2
      protocol: TCP
      port: 9300