---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elastic-stack
  name: kibana
data:
  kibana.yml: |-
    server:
      basePath: "/kibana"
      name: kibana
      host: "0.0.0.0"

    elasticsearch:
      hosts: ["http://elasticsearch.elastic-stack.svc.cluster.local:9200"]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      volumes:
        - name: kibana-config
          configMap:
            name: kibana
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.6.1
          volumeMounts:
            - mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
              name: kibana-config

---

apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  selector:
    app: kibana
  ports:
    -  port: 5601

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: elastic-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
    - http:
        paths:
          - path: /kibana/(.*)
            backend:
              serviceName: kibana
              servicePort: 5601
