---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: elastic-stack
data:
  kibana.yml: |-
    server.port: 8080
    elasticsearch.hosts: [ "http://elastic-stack.elasticsearch:9200" ]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.6.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
              name: kibana-conifg
      volumes:
       - name: kibana-conifg
         configMap:
           name: kibana

---

apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-stack
  labels:
    app: kibana

spec:
  selector:
    app: kibana
  ports:
    - name: kibana-tcp
      port: 8080
      protocol: TCP

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: elastic-stack
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: kibana
              servicePort: 8080
